[package]
name = "virtualkey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-protocols = { version = "0.30.0", default-features = false, features = [
	"unstable",
	"client",
] }
#wayland-protocols = { version = "=0.30.0-beta.13", features = ["client", "unstable"] }


wayland-protocols-wlr = { version = "0.1.0", default-features = false, features = [
	"client",
] }
wayland-client = { version = "0.30.2"}

wayland-protocols-misc = { version = "0.1.0", features = ["client"] }
xkbcommon = "0.5.0"
tempfile = "3.5.0"
thiserror = "1.0.47"
